/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // ---- Institutional palette: deep navy / warm ivory / muted gold / restrained teal ----
        error: "#B42318",
        "surface-variant": "#E7E1D3",
        "on-tertiary-fixed": "#13243A",
        "surface-bright": "#FBFAF6",
        "on-primary-fixed-variant": "#3f465c",
        surface: "#F6F3ED",
        "primary-fixed": "#dae2fd",
        "surface-container-high": "#EAE4D6",
        "surface-dim": "#DCD5C4",
        "secondary-container": "#0E3E3B",
        "on-error-container": "#7A170F",
        "on-surface-variant": "#5B5546",
        "on-primary-container": "#7c839b",
        "error-container": "#F7DCD8",
        "secondary-fixed-dim": "#5FA8A2",
        "on-error": "#ffffff",
        "inverse-primary": "#9FCFCB",
        secondary: "#287C78",
        tertiary: "#000000",
        "surface-tint": "#565e74",
        "secondary-fixed": "#D9EEEC",
        "surface-container-lowest": "#ffffff",
        primary: "#0B1628",
        "outline-variant": "#D6CFBD",
        "on-secondary-fixed": "#0E3E3B",
        background: "#F6F3ED",
        "inverse-on-surface": "#eff1f3",
        "on-secondary-fixed-variant": "#0E3E3B",
        "on-background": "#0B1628",
        outline: "#8A8371",
        "primary-container": "#13243A",
        "on-primary-fixed": "#13243A",
        "on-surface": "#0B1628",
        "surface-container-low": "#F1EDE3",
        "surface-container-highest": "#E3DCCC",
        "tertiary-container": "#13243A",
        "tertiary-fixed-dim": "#b9c7df",
        "on-tertiary": "#ffffff",
        "on-primary": "#ffffff",
        "on-tertiary-fixed-variant": "#3a485b",
        "on-secondary-container": "#D9EEEC",
        "on-secondary": "#ffffff",
        "inverse-surface": "#2d3133",
        "surface-container": "#EDE8DB",
        "tertiary-fixed": "#d5e3fc",
        "primary-fixed-dim": "#bec6e0",
        "on-tertiary-container": "#77859a",
        // Deep navy — hero/header bands, dark chrome
        navy: "#0B1628",
        "navy-light": "#13243A",
        // Muted institutional gold — the signature accent (CTAs, active states, rules)
        gold: {
          DEFAULT: "#B89B5E",
          light: "#D6C08C",
          dark: "#8A7240",
        },
        // Restrained teal — secondary accent (links, informational badges)
        teal: {
          DEFAULT: "#287C78",
          light: "#5FA8A2",
          dark: "#0E3E3B",
        },
      },
      keyframes: {
        floatY: {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-14px)" },
        },
        glowPulse: {
          "0%, 100%": { opacity: "0.55" },
          "50%": { opacity: "1" },
        },
      },
      animation: {
        floatY: "floatY 6s ease-in-out infinite",
        glowPulse: "glowPulse 4s ease-in-out infinite",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        four: "4px",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "stack-sm": "8px",
        "margin-desktop": "40px",
        "margin-mobile": "16px",
        gutter: "24px",
        base: "4px",
        "stack-lg": "32px",
        "stack-md": "16px",
      },
      fontFamily: {
        "body-lg": ["Lato", "sans-serif"],
        "label-md": ["Lato", "sans-serif"],
        "headline-sm": ['"EB Garamond"', "serif"],
        "headline-md": ['"EB Garamond"', "serif"],
        "headline-lg-mobile": ['"EB Garamond"', "serif"],
        "display-lg": ['"EB Garamond"', "serif"],
        "headline-lg": ['"EB Garamond"', "serif"],
        "body-sm": ["Lato", "sans-serif"],
        "body-md": ["Lato", "sans-serif"],
        // Evidence font — every score, date, CNR number, and count on the
        // site is set in this instead of the browser's generic monospace
        // default, so figures read as instrumented fact ("the arithmetic"),
        // visually distinct from the serif/sans used for narrative text.
        mono: ['"IBM Plex Mono"', "ui-monospace", "monospace"],
        evidence: ['"IBM Plex Mono"', "ui-monospace", "monospace"],
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-md": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" },
        ],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-lg-mobile": [
          "28px",
          { lineHeight: "36px", fontWeight: "600" },
        ],
        "display-lg": [
          "48px",
          { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
