/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        error: "#ba1a1a",
        "surface-variant": "#e0e3e5",
        "on-tertiary-fixed": "#0d1c2e",
        "surface-bright": "#f7f9fb",
        "on-primary-fixed-variant": "#3f465c",
        surface: "#f7f9fb",
        "primary-fixed": "#dae2fd",
        "surface-container-high": "#e6e8ea",
        "surface-dim": "#d8dadc",
        "secondary-container": "#316bf3",
        "on-error-container": "#93000a",
        "on-surface-variant": "#45464d",
        "on-primary-container": "#7c839b",
        "error-container": "#ffdad6",
        "secondary-fixed-dim": "#b4c5ff",
        "on-error": "#ffffff",
        "inverse-primary": "#bec6e0",
        secondary: "#0051d5",
        tertiary: "#000000",
        "surface-tint": "#565e74",
        "secondary-fixed": "#dbe1ff",
        "surface-container-lowest": "#ffffff",
        primary: "#000000",
        "outline-variant": "#c6c6cd",
        "on-secondary-fixed": "#00174b",
        background: "#f7f9fb",
        "inverse-on-surface": "#eff1f3",
        "on-secondary-fixed-variant": "#003ea8",
        "on-background": "#191c1e",
        outline: "#76777d",
        "primary-container": "#131b2e",
        "on-primary-fixed": "#131b2e",
        "on-surface": "#191c1e",
        "surface-container-low": "#f2f4f6",
        "surface-container-highest": "#e0e3e5",
        "tertiary-container": "#0d1c2e",
        "tertiary-fixed-dim": "#b9c7df",
        "on-tertiary": "#ffffff",
        "on-primary": "#ffffff",
        "on-tertiary-fixed-variant": "#3a485b",
        "on-secondary-container": "#fefcff",
        "on-secondary": "#ffffff",
        "inverse-surface": "#2d3133",
        "surface-container": "#eceef0",
        "tertiary-fixed": "#d5e3fc",
        "primary-fixed-dim": "#bec6e0",
        "on-tertiary-container": "#77859a",
        // Navy accents used directly in the Stitch mockups (hero CTA, impact band, header)
        navy: "#0F172A",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        four: "4px",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "stack-sm": "8px",
        "margin-desktop": "40px",
        "margin-mobile": "16px",
        gutter: "24px",
        base: "4px",
        "stack-lg": "32px",
        "stack-md": "16px",
      },
      fontFamily: {
        "body-lg": ["Public Sans", "sans-serif"],
        "label-md": ["Public Sans", "sans-serif"],
        "headline-sm": ['"Source Serif 4"', "serif"],
        "headline-md": ['"Source Serif 4"', "serif"],
        "headline-lg-mobile": ['"Source Serif 4"', "serif"],
        "display-lg": ['"Source Serif 4"', "serif"],
        "headline-lg": ['"Source Serif 4"', "serif"],
        "body-sm": ["Public Sans", "sans-serif"],
        "body-md": ["Public Sans", "sans-serif"],
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-md": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" },
        ],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-lg-mobile": [
          "28px",
          { lineHeight: "36px", fontWeight: "600" },
        ],
        "display-lg": [
          "48px",
          { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
